drop table if exists superstore_sales

-- Create table 
CREATE TABLE superstore_sales (
	row_id int, 
	order_id varchar(50), 
	order_date varchar(20), 
	ship_date varchar(20), 
	ship_mode varchar(50), 
	customer_id varchar(50), 
	customer_name varchar(255), 
	segment varchar(50), 
	country varchar(50), 
	city varchar(50), 
	state varchar(50), 
	postal_code varchar(20), 
	region varchar(50), 
	product_id varchar(50), 
	category varchar(100), 
	sub_category varchar(100), 
	product_name varchar(255), 
	sales numeric
);

-- Import data from csv 
COPY superstore_sales
FROM '/Users/swati/Documents/Python + ML Practice Notebooks/SQL Superstore Training Dataset/train.csv'
DELIMITER ','
CSV HEADER;

-- Confirm data is loaded successfully 
select * from superstore_sales

-- Data Cleaning -> Convert date columns from varchar to date type 
update superstore_sales 
	set order_date = to_date(order_date, 'DD/MM/YYYY'), 
	ship_date = to_date(ship_date, 'DD/MM/YYYY');

alter table superstore_sales 
alter column order_date type date using order_date::date, 
alter column ship_date type date using ship_date::date;

select * from superstore_sales

-- Show first 10 rows 
select * from superstore_sales limit 10

-- count total orders
select count(*) from superstore_sales

-- list all unique categories
select distinct category from superstore_sales;

-- total sales
select sum(sales) from superstore_sales

-- sales by category (highest first)
select category, sum(sales) as total_sales from superstore_sales group by category order by total_sales desc

-- sales by region
select region, sum(sales) as total_sales from superstore_sales group by region order by total_sales desc

-- number of orders per customer
select customer_id, customer_name, count(*) as total_orders 
	from superstore_sales group by customer_id, customer_name order by total_orders desc

-- top 10 highest selling products 
select product_id, product_name, sum(sales) as sales 
	from superstore_sales 
	group by product_id, product_name 
	order by sales desc 
	limit 10

-- month on month sales trend 
select date_trunc('month', order_date) as month, sum(sales) as monthly_sales 
	from superstore_sales 
	group by month 
	order by month

-- average shipping delay in days 
select avg(ship_date - order_date) as avg_shipping_delay from superstore_sales

-- state-wise sales + rank
select state, sum(sales) as total_sales, rank() over (order by sum(sales) desc) as sales_rank 
	from superstore_sales 
	group by state 

-- duplicated orders (same order_id)
select order_id, count(*) as count from superstore_sales group by order_id having count(*) > 1

-- most popular sub-category in each region
select region, sub_category, total_sales 
	from (
		select region, sub_category, sum(sales) as total_sales, row_number() over 
			(partition by region order by sum(sales) desc) as rn
			from superstore_sales group by region, sub_category
	) t
	where rn = 1

-- Customer LifeTime Value
select customer_id, customer_name, sum(sales) as lifetime_value 
	from superstore_sales 
	group by customer_id, customer_name 
	order by lifetime_value desc

-- Cohort Analysis - First Purchase Month + Total Sales
-- Group customers based on the month in which they made their first purchase, 
-- and then calculate the total sales generated by each cohort over time
-- Cohort means all customers whose first purchase happened in the same month
with first_purchase as (
	select customer_id, min(order_date) as first_order_date 
	from superstore_sales group by customer_id
) select date_trunc('month', first_purchase.first_order_date) as cohort_month, sum(sales) as total_sales 
	from first_purchase join superstore_sales using(customer_id) group by cohort_month 
	order by cohort_month

-- RFM Scoring Model - Recency, Frequency, Monetary
-- Understand customer behavior and segment customers based on how recently, 
-- how often, and how much they purchase
select customer_id, 
	(CURRENT_DATE - max(order_date)) as recency, 
	count(order_id) as frequency, 
	sum(sales) as monetary 
	from superstore_sales 
	group by customer_id 
	order by monetary desc